# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Programacao\Projetos\ProjetoBarbearia\telas\tela_calendario_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_calendario_cliente(object):
    def setupUi(self, Tela_calendario_cliente):
        Tela_calendario_cliente.setObjectName("Tela_calendario_cliente")
        Tela_calendario_cliente.resize(1000, 700)
        Tela_calendario_cliente.setMinimumSize(QtCore.QSize(1000, 700))
        Tela_calendario_cliente.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(Tela_calendario_cliente)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 130, 911, 411))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 640, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 640, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 50, 911, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 90, 911, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(40, 550, 911, 81))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView.setObjectName("listView")
        Tela_calendario_cliente.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Tela_calendario_cliente)
        self.statusbar.setObjectName("statusbar")
        Tela_calendario_cliente.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_calendario_cliente)
        QtCore.QMetaObject.connectSlotsByName(Tela_calendario_cliente)

    def retranslateUi(self, Tela_calendario_cliente):
        _translate = QtCore.QCoreApplication.translate
        Tela_calendario_cliente.setWindowTitle(_translate("Tela_calendario_cliente", "MainWindow"))
        self.pushButton.setText(_translate("Tela_calendario_cliente", "Sair"))
        self.pushButton_2.setText(_translate("Tela_calendario_cliente", "Confirmar"))
        self.label_5.setText(_translate("Tela_calendario_cliente", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Nome :</span></p></body></html>"))
        self.label_3.setText(_translate("Tela_calendario_cliente", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Email :</span></p></body></html>"))
