# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Programacao\Projetos\ProjetoBarbearia\telas\tela_barbeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Barbeiro(object):
    def setupUi(self, Tela_Barbeiro):
        Tela_Barbeiro.setObjectName("Tela_Barbeiro")
        Tela_Barbeiro.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tela_Barbeiro.sizePolicy().hasHeightForWidth())
        Tela_Barbeiro.setSizePolicy(sizePolicy)
        Tela_Barbeiro.setMinimumSize(QtCore.QSize(1000, 700))
        Tela_Barbeiro.setMaximumSize(QtCore.QSize(1000, 700))
        Tela_Barbeiro.setAcceptDrops(False)
        Tela_Barbeiro.setDocumentMode(True)
        Tela_Barbeiro.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Tela_Barbeiro)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 80, 62, 21))
        self.label_2.setObjectName("label_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setGeometry(QtCore.QRect(210, 130, 601, 401))
        self.calendarWidget.setAcceptDrops(False)
        self.calendarWidget.setSelectedDate(QtCore.QDate(2024, 2, 10))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 30, 139, 33))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 640, 132, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 640, 105, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 630, 105, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setEnabled(True)
        self.listView.setGeometry(QtCore.QRect(210, 550, 601, 81))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView.setObjectName("listView")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(860, 630, 114, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        Tela_Barbeiro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Tela_Barbeiro)
        self.statusbar.setObjectName("statusbar")
        Tela_Barbeiro.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_Barbeiro)
        QtCore.QMetaObject.connectSlotsByName(Tela_Barbeiro)

    def retranslateUi(self, Tela_Barbeiro):
        _translate = QtCore.QCoreApplication.translate
        Tela_Barbeiro.setWindowTitle(_translate("Tela_Barbeiro", "MainWindow"))
        self.label_2.setText(_translate("Tela_Barbeiro", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Barbeiro</span></p></body></html>"))
        self.label.setText(_translate("Tela_Barbeiro", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">BARBEARIA</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Tela_Barbeiro", "Marcar na Agenda"))
        self.pushButton.setText(_translate("Tela_Barbeiro", "Ver marcações"))
        self.pushButton_3.setText(_translate("Tela_Barbeiro", "Sair"))
        self.pushButton_4.setText(_translate("Tela_Barbeiro", "Ver Agenda"))
