# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Programacao\Projetos\ProjetoBarbearia\telas\Tela_Buscar_Barbeiro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_busca_Barbeiro(object):
    def setupUi(self, Tela_busca_Barbeiro):
        Tela_busca_Barbeiro.setObjectName("Tela_busca_Barbeiro")
        Tela_busca_Barbeiro.resize(1000, 700)
        Tela_busca_Barbeiro.setMinimumSize(QtCore.QSize(1000, 700))
        Tela_busca_Barbeiro.setMaximumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(Tela_busca_Barbeiro)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 630, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 139, 33))
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(40, 130, 891, 461))
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView.setObjectName("listView")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 600, 147, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 60, 62, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 100, 79, 21))
        self.label_4.setObjectName("label_4")
        Tela_busca_Barbeiro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Tela_busca_Barbeiro)
        self.statusbar.setObjectName("statusbar")
        Tela_busca_Barbeiro.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_busca_Barbeiro)
        QtCore.QMetaObject.connectSlotsByName(Tela_busca_Barbeiro)

    def retranslateUi(self, Tela_busca_Barbeiro):
        _translate = QtCore.QCoreApplication.translate
        Tela_busca_Barbeiro.setWindowTitle(_translate("Tela_busca_Barbeiro", "MainWindow"))
        self.pushButton.setText(_translate("Tela_busca_Barbeiro", "Voltar"))
        self.label.setText(_translate("Tela_busca_Barbeiro", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">BARBEARIA</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Tela_busca_Barbeiro", "Liberar Datas e horarios"))
        self.label_3.setText(_translate("Tela_busca_Barbeiro", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Barbeiro</span></p></body></html>"))
        self.label_4.setText(_translate("Tela_busca_Barbeiro", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Marcações</span></p></body></html>"))
